
---
spring:
  profiles: discovery1
eureka:
  instance:
    hostname: discovery1
  client:
    serviceUrl:
      defaultZone: http://discovery2/eureka/

---
spring:
  profiles: discovery2
eureka:
  instance:
    hostname: discovery2
  client:
    serviceUrl:
      defaultZone: http://discovery1/eureka/
      
---
spring:
  profiles: chip1
eureka:
  instance:
    hostname: chip1
  client:
    serviceUrl:
      defaultZone: http://chip2:8761/eureka/
    healthcheck: true
    register-with-eureka: true
    fetch-registry: true
---
spring:
  profiles: chip2
eureka:
  instance:
    hostname: chip2
    instance-id: 
  client:
    serviceUrl:
      defaultZone: http://chip1:8761/eureka/
    healthcheck: true
    register-with-eureka: true
    fetch-registry: true
    